### ISSUE TITLE
Port to GNOME 47

### ISSUE THREAD

**Issue by antrmn** [marcinjahn/gnome-do-not-disturb-while-screen-sharing-or-recording-extension#1]
GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

Thanks!

**Comment by hedgieinsocks** [comment]
For what is worth, just upgraded to fedora 41 and it works there :+1:

**Comment by marcinjahn** [comment]
@hedgieinsocks Did you have a chance to check both screen recording and screen sharing? If so, and it works, I’d accept a PR where you add 47 to supported versions.

**Comment by marcinjahn** [comment]
The new version is active on https://extensions.gnome.org/extension/5985/do-not-disturb-while-screen-sharing-or-recording/.

Again, thanks for your PR.
